#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 100     # Set DPI. User may want to use a larger number for larger screens.
setbg &              # set the background with the `setbg` script
xrdb ~/.Xresources & # Uncomment to use Xresources colors/settings on startup
remaps &             # run the remaps script, switching caps/esc and more; check it for more info
blueman-applet &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
# MS &
picom --experimental-backends -b &
# zathura ~/.scripts/dokoddo/dokoddo.pdf &
# xrootgif ~/Pictures/Patreon.gif &&
autostart="mpd dunst unclutter pipewire"

xinput set-prop "Microsoft Surface 045E:09AF Touchpad" "Device Enabled" 0

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
